package net.hearthstats.game.imageanalysis

import java.awt.image.BufferedImage

import UniquePixel._

class HsClassAnalyser extends ImageAnalyser {

  def imageIdentifyYourClass(image: BufferedImage): Option[String] =
    identify(image, Seq(
      Array(YOUR_DRUID_1, YOUR_DRUID_2, YOUR_DRUID_3) -> "Druid",
      Array(YOUR_HUNTER_1, YOUR_HUNTER_2, YOUR_HUNTER_3) -> "Hunter",
      Array(YOUR_MAGE_1, YOUR_MAGE_2, YOUR_MAGE_3) -> "Mage",
      Array(YOUR_PALADIN_1, YOUR_PALADIN_2, YOUR_PALADIN_3) -> "Paladin",
      Array(YOUR_PRIEST_1, YOUR_PRIEST_2, YOUR_PRIEST_3) -> "Priest",
      Array(YOUR_ROGUE_1, YOUR_ROGUE_2, YOUR_ROGUE_3) -> "Rogue",
      Array(YOUR_SHAMAN_1, YOUR_SHAMAN_2, YOUR_SHAMAN_3) -> "Shaman",
      Array(YOUR_WARLOCK_1, YOUR_WARLOCK_2, YOUR_WARLOCK_3) -> "Warlock",
      Array(YOUR_WARRIOR_1, YOUR_WARRIOR_2, YOUR_WARRIOR_3) -> "Warrior",
      Array(YOUR_DRUID_GOLDEN_1, YOUR_DRUID_GOLDEN_2, YOUR_DRUID_GOLDEN_3) -> "Druid",
      Array(YOUR_HUNTER_GOLDEN_1, YOUR_HUNTER_GOLDEN_2, YOUR_HUNTER_GOLDEN_3) -> "Hunter",
      Array(YOUR_MAGE_GOLDEN_1, YOUR_MAGE_GOLDEN_2, YOUR_MAGE_GOLDEN_3) -> "Mage",
      Array(YOUR_ROGUE_GOLDEN_1, YOUR_ROGUE_GOLDEN_2, YOUR_ROGUE_GOLDEN_3) -> "Rogue",
      Array(YOUR_SHAMAN_GOLDEN_1, YOUR_SHAMAN_GOLDEN_2, YOUR_SHAMAN_GOLDEN_3) -> "Shaman",
      Array(YOUR_WARLOCK_GOLDEN_1, YOUR_WARLOCK_GOLDEN_2, YOUR_WARLOCK_GOLDEN_3) -> "Warlock",
      Array(YOUR_WARRIOR_GOLDEN_1, YOUR_WARRIOR_GOLDEN_2, YOUR_WARRIOR_GOLDEN_3) -> "Warrior"))

  def imageIdentifyOpponentClass(image: BufferedImage): Option[String] =
    identify(image, Seq(
      Array(OPPONENT_DRUID_1, OPPONENT_DRUID_2, OPPONENT_DRUID_3) -> "Druid",
      Array(OPPONENT_HUNTER_1, OPPONENT_HUNTER_2, OPPONENT_HUNTER_3) -> "Hunter",
      Array(OPPONENT_MAGE_1, OPPONENT_MAGE_2, OPPONENT_MAGE_3) -> "Mage",
      Array(OPPONENT_PALADIN_1, OPPONENT_PALADIN_2, OPPONENT_PALADIN_3) -> "Paladin",
      Array(OPPONENT_PRIEST_1, OPPONENT_PRIEST_2, OPPONENT_PRIEST_3) -> "Priest",
      Array(OPPONENT_ROGUE_1, OPPONENT_ROGUE_2, OPPONENT_ROGUE_3) -> "Rogue",
      Array(OPPONENT_SHAMAN_1, OPPONENT_SHAMAN_2, OPPONENT_SHAMAN_3) -> "Shaman",
      Array(OPPONENT_WARLOCK_1, OPPONENT_WARLOCK_2, OPPONENT_WARLOCK_3) -> "Warlock",
      Array(OPPONENT_WARRIOR_1, OPPONENT_WARRIOR_2, OPPONENT_WARRIOR_3) -> "Warrior",
      Array(OPPONENT_DRUID_GOLDEN_1, OPPONENT_DRUID_GOLDEN_2, OPPONENT_DRUID_GOLDEN_3) -> "Druid",
      Array(OPPONENT_HUNTER_GOLDEN_1, OPPONENT_HUNTER_GOLDEN_2, OPPONENT_HUNTER_GOLDEN_3) -> "Hunter",
      Array(OPPONENT_MAGE_GOLDEN_1, OPPONENT_MAGE_GOLDEN_2, OPPONENT_MAGE_GOLDEN_3) -> "Mage",
      Array(OPPONENT_PALADIN_GOLDEN_1, OPPONENT_PALADIN_GOLDEN_2, OPPONENT_PALADIN_GOLDEN_3) -> "Paladin",
      Array(OPPONENT_PRIEST_GOLDEN_1, OPPONENT_PRIEST_GOLDEN_2, OPPONENT_PRIEST_GOLDEN_3) -> "Priest",
      Array(OPPONENT_ROGUE_GOLDEN_1, OPPONENT_ROGUE_GOLDEN_2, OPPONENT_ROGUE_GOLDEN_3) -> "Rogue",
      Array(OPPONENT_SHAMAN_GOLDEN_1, OPPONENT_SHAMAN_GOLDEN_2, OPPONENT_SHAMAN_GOLDEN_3) -> "Shaman",
      Array(OPPONENT_WARLOCK_GOLDEN_1, OPPONENT_WARLOCK_GOLDEN_2, OPPONENT_WARLOCK_GOLDEN_3) -> "Warlock",
      Array(OPPONENT_WARRIOR_GOLDEN_1, OPPONENT_WARRIOR_GOLDEN_2, OPPONENT_WARRIOR_GOLDEN_3) -> "Warrior"))

}